mysql_user: "root"
mysql_password: "root"


# Springboard will be cloned into springboard-valet/sites/[projectroot]
# The site will have the hostname [projectroot].test
# Don't use any special characters in the projectroot. Only a-z, "_", and "-" are allowed.
projects:
  - Description of my project
    projectroot: "myproject"

  - Description of my other project
    projectroot: "myotherproject"